### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by gamesfreak26** [gamesfreak26/mern-backend#3]
Github Actions are failing.  I think it's because it can't access the test database as it's a localhost database.

**Comment by gamesfreak26** [comment]
Added MongoDB action as per https://futurestud.io/tutorials/github-actions-using-mongodb however, tests are still failing.  Not sure why at the moment.  


```
Run npm test

> mern-backend@1.0.0 test /home/runner/work/mern-backend/mern-backend
> mocha

(node:2530) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)


Connected to database!
  get all products
Length of Object: 0
    1) should get all posts that exist


  0 passing (54ms)
  1 failing

  1) get all products
       should get all posts that exist:

      Uncaught AssertionError: expected 0 to equal 1
      + expected - actual

      -0
      +1
      
      at /home/runner/work/mern-backend/mern-backend/test/product_utils.test.js:55:39
      at /home/runner/work/mern-backend/mern-backend/node_modules/mongoose/lib/model.js:4870:16
      at /home/runner/work/mern-backend/mern-backend/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
      at /home/runner/work/mern-backend/mern-backend/node_modules/mongoose/lib/model.js:4893:21
      at /home/runner/work/mern-backend/mern-backend/node_modules/mongoose/lib/query.js:4400:11
      at /home/runner/work/mern-backend/mern-backend/node_modules/kareem/index.js:136:16
      at processTicksAndRejections (internal/process/task_queues.js:75:11)



npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
```

**Comment by gamesfreak26** [comment]
It looks like local tests are failing as well.

**Comment by gamesfreak26** [comment]
Issue was caused by having not awaiting an async function.  Closing issue.
